name: flechette
description: lightweight dart extensions.
version: 0.0.1+20220113
homepage: https://github.com/i10416/dart-modules/flechette

environment:
  sdk: ">=2.12.0 <3.0.0"



dev_dependencies:
  test: ^1.17.11
