name: flechette
description: This package provides lightweight syntax extensions and general purpose helper classes.
version: 0.1.0
homepage: https://github.com/i10416/dart-modules/tree/master/flechette

environment:
  sdk: "<4.0.0"



dev_dependencies:
  test: ^1.17.11
