name: flechette
description: This package provides lightweight syntax extensions and general purpose helper classes.
version: 0.0.1
homepage: https://github.com/i10416/dart-modules/tree/master/flechette

environment:
  sdk: ">=2.12.0 <3.0.0"



dev_dependencies:
  test: ^1.17.11
