name: flechette
description: lightweight dart extensions.
version: 0.0.1
homepage: https://github.com/ItoYo16u/dart-modules/flechette

environment:
  sdk: ">=2.12.0 <3.0.0"



dev_dependencies:
  lint: ^1.6.0
  test: ^1.17.11
