name: arches_example
description: Demonstrates how to use the arches.

publish_to: 'none'

environment:
  sdk: "<4.0.0"

dependencies:
  flutter:
    sdk: flutter

  arches:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true